name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: FnControlOption/unicode-properties-zig
    - name: Generate Docs
      run: zig build-lib -femit-docs unicode_properties.zig
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
